import ReactQueryProvider from "./_Components/ReactQueryProvider";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <ReactQueryProvider>
          <div className="min-h-screen size-full">{children}</div>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
